### ISSUE TITLE
What is going on with settings !

### ISSUE THREAD

**Issue by moghir2004** [kurtr/devRantCLI#2]
I wish I could help with JS but i can't actually settings doesn't work it closes the command.....

**Comment by jacobgc** [comment]
I'm sorry but this bug report is worthy of being posted to devRant as being one of the worst bug reports going...

**Comment by kurtr** [comment]
Nothings going on with settings, like seriously it's almost like there's no code or something. That damn methods been acting so fake lately it might as well just be a fricken place holder!

Closing since settings and I haven't touched base in a while and every time I try it just closes down on me and I really don't like it's attitude. Maybe you should rant about it....
